import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='mx-auto' lang="en">
      <body className={inter.className}>
        <nav className='flex justify-between items-center text-3xl bold border border-black border-b-2 p-5 w-full'>
          <Link href='/product' className=''>Buy Here</Link>
          <Link href='/about' className=''>About</Link>
          <img src='vercel.svg' height={200} width={200}></img> 
          <Link href='/contact' className=''>Contact</Link>
          <Link href='/cart' className=''>Cart</Link> 
        </nav>
      {children}
      </body>
    </html>
  )
}
